application: snake-mercury
version: 2
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

inbound_services:
- warmup
- mail

handlers:
- url: /static
  static_dir: static

- url: /static/admin
  static_dir: static/admin

#- url: /admin
#  static_dir: static/admin

- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/images/favicon\.ico

- url: /.*
  script: djangoappengine.main.application
